fix: updated release workflow
contentstack/datasync-filesystem-sdk pull request #24
Opened 2023-02-16 06:40 UTC by abhinav-from-contentstack

2023-02-16 10:42 UTC, netrajpatel approved these changes

2023-02-16 10:45 UTC, netrajpatel requested changes
@abhinav-from-contentstack 
Add a note for package version updates

2023-02-16 10:54 UTC, abhinav-from-contentstack commented
done @netrajpatel

2023-02-16 10:55 UTC, netrajpatel approved these changes

2023-02-28 06:13 UTC, abhinav-from-contentstack commented
Merged this PR into #23

2023-02-28 06:13 UTC, closed without merging